apiVersion: v1
kind: Service
metadata:
  name: tfm-vets-service-service
  labels:
    type: tfm
spec:
  ports:
  - name: "8083"
    port: 8083
    targetPort: 8083
  selector:
    app: tfm-vets-service
