apiVersion: apps/v1
kind: Deployment
metadata:
  name: tfm-vets-service
  labels:
    app: tfm-vets-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tfm-vets-service
  template:
    metadata:
      labels:
        app: tfm-vets-service
    spec:
      containers:
      - name: spring-petclinic-vets-service
        image: mintakorion/spring-petclinic-vets-service:2.2.2-SNAPSHOT
        ports:
        - containerPort: 8083
        resources:
          limits:
            memory: 512Mi
          requests:
            memory: 128Mi
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 8083
          initialDelaySeconds: 40
          timeoutSeconds: 2
          periodSeconds: 10
          failureThreshold: 2
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8083
          initialDelaySeconds: 100
          timeoutSeconds: 2
          periodSeconds: 10
          failureThreshold: 1
