version: '2'

services:
  config-server:
    image: nespasec/spring-petclinic-config-server:2.2.1
    container_name: config-server
    mem_limit: 512M    
    ports:
     - 8888:8888

  discovery-server:
    image: nespasec/spring-petclinic-discovery-server:2.2.1
    container_name: discovery-server
    mem_limit: 512M
    depends_on:
      - config-server
    entrypoint: ["./dockerize","-wait=tcp://config-server:8888","-timeout=60s","--","java","-XX:+UnlockExperimentalVMOptions", "-XX:+UseCGroupMemoryLimitForHeap", "-Djava.security.egd=file:/dev/./urandom","-cp", "/app/resources:/app/classes:/app/libs/*", "org.springframework.samples.petclinic.discovery.DiscoveryServerApplication"]
    ports:
      - 8761:8761

  customers-service:
    image: nespasec/spring-petclinic-customers-service:2.2.1
    container_name: customers-service
    mem_limit: 512M
    depends_on:
     - config-server
     - discovery-server
    entrypoint: ["./dockerize","-wait=tcp://discovery-server:8761","-timeout=60s","--","java", "-XX:+UnlockExperimentalVMOptions", "-XX:+UseCGroupMemoryLimitForHeap", "-Djava.security.egd=file:/dev/./urandom","-cp", "/app/resources:/app/classes:/app/libs/*", "org.springframework.samples.petclinic.customers.CustomersServiceApplication"]
    ports:
    - 8081:8081

  visits-service:
    image: nespasec/spring-petclinic-visits-service:2.2.1
    container_name: visits-service
    mem_limit: 512M
    depends_on:
      - config-server
      - discovery-server
    entrypoint: ["./dockerize","-wait=tcp://discovery-server:8761","-timeout=60s","--","java", "-XX:+UnlockExperimentalVMOptions", "-XX:+UseCGroupMemoryLimitForHeap", "-Djava.security.egd=file:/dev/./urandom","-cp", "/app/resources:/app/classes:/app/libs/*", "org.springframework.samples.petclinic.visits.VisitsServiceApplication"]      
    ports:
      - 8082:8082
  
  vets-service:
    image: nespasec/spring-petclinic-vets-service:2.2.1
    container_name: vets-service
    mem_limit: 512M
    depends_on:
      - config-server
      - discovery-server
    entrypoint: ["./dockerize","-wait=tcp://discovery-server:8761","-timeout=60s","--","java", "-XX:+UnlockExperimentalVMOptions", "-XX:+UseCGroupMemoryLimitForHeap", "-Djava.security.egd=file:/dev/./urandom","-cp", "/app/resources:/app/classes:/app/libs/*", "org.springframework.samples.petclinic.vets.VetsServiceApplication"]
    ports:
      - 8083:8083
  
  api-gateway:
    image: nespasec/spring-petclinic-api-gateway:2.2.1
    container_name: api-gateway
    mem_limit: 512M
    depends_on:
      - config-server
      - discovery-server
    entrypoint: ["./dockerize","-wait=tcp://discovery-server:8761","-timeout=60s","--","java", "-XX:+UnlockExperimentalVMOptions", "-XX:+UseCGroupMemoryLimitForHeap", "-Djava.security.egd=file:/dev/./urandom","-cp", "/app/resources:/app/classes:/app/libs/*", "org.springframework.samples.petclinic.api.ApiGatewayApplication"]
    ports:
      - 8080:8080
  
  tracing-server:
    image: openzipkin/zipkin
    container_name: tracing-server
    mem_limit: 512M
    environment:
    - JAVA_OPTS=-XX:+UnlockExperimentalVMOptions -Djava.security.egd=file:/dev/./urandom
    ports:
       - 9411:9411
  
  admin-server:
    image: nespasec/spring-petclinic-admin-server:2.2.1
    container_name: admin-server
    mem_limit: 512M
    depends_on:
      - config-server
      - discovery-server
    entrypoint: ["./dockerize","-wait=tcp://discovery-server:8761","-timeout=60s","--","java", "-XX:+UnlockExperimentalVMOptions", "-XX:+UseCGroupMemoryLimitForHeap", "-Djava.security.egd=file:/dev/./urandom","-cp", "/app/resources:/app/classes:/app/libs/*", "org.springframework.samples.petclinic.admin.SpringBootAdminApplication"]
    ports:
      - 9090:9090
         
  ## Grafana / Prometheus

  grafana-server:
    build: ./docker/grafana
    container_name: grafana-server
    mem_limit: 256M
    ports:
    - 3000:3000

  prometheus-server:
    build: ./docker/prometheus
    container_name: prometheus-server
    mem_limit: 256M
    ports:
    - 9091:9090
