apiVersion: v1
kind: Service
metadata:
  name: tfm-grafana-service
  annotations:
      prometheus.io/scrape: 'true'
      prometheus.io/port:   '3000'
spec:
  selector: 
    app: tfm-grafana    
  ports:
    - port: 3000
      targetPort: 3000