apiVersion: v1
kind: Service
metadata:
  name: tfm-customers-service-service
  labels:
    type: tfm
spec:
  ports:
  - name: "8081"
    port: 8081
    targetPort: 8081
  selector:
    app: tfm-customers-service
