apiVersion: apps/v1
kind: Deployment
metadata:
  name: tfm-customers-service
  labels:
    app: tfm-customers-service
    tfm: "true"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: tfm-customers-service
  template:
    metadata:
      labels:
        app: tfm-customers-service
    spec:
      containers:
      - name: spring-petclinic-customers-service
        image: nespasec/spring-petclinic-customers-service:2.2.2-SNAPSHOT
        ports:
        - containerPort: 8081
        resources:
          limits:
            memory: 512Mi
          requests:
            memory: 128Mi
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 8081
          initialDelaySeconds: 40
          timeoutSeconds: 2
          periodSeconds: 10
          failureThreshold: 2
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8081
          initialDelaySeconds: 100
          timeoutSeconds: 2
          periodSeconds: 10
          failureThreshold: 1
          