apiVersion: v1
kind: Service
metadata:
  name: tfm-visits-service-service
  labels:
    type: tfm
spec:
  ports:
  - name: "8082"
    port: 8082
    targetPort: 8082
  selector:
    app: tfm-visits-service