apiVersion: v1
kind: Service
metadata:
  name: tfm-admin-server-service
  labels:
    type: tfm
spec:
  ports:
  - name: "9090"
    port: 9090
    targetPort: 9090
  selector:
    app: tfm-admin-server