apiVersion: v1
kind: ConfigMap
metadata:
  name: tfm-grafana-datasources-provider
data:
  datasources.yaml: |-
    # config file version
    apiVersion: 1

    # list of datasources to insert/update depending what's available in the database
    datasources:
    - name: Prometheus
      type: prometheus
      access: proxy
      org_id: 1
      url: http://tfm-prometheus-service:9100
      is_default: true
      version: 1
      editable: true