apiVersion: v1
kind: Service
metadata:
  name: tfm-config-server-service
  labels:
    type: tfm
spec:
  ports:
  - name: "8888"
    port: 8888
    targetPort: 8888
  selector:
    app: tfm-config-server
