apiVersion: apps/v1
kind: Deployment
metadata:
  name: tfm-config-server
  labels:
    app: tfm-config-server
    tfm: "true"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tfm-config-server     
  template:
    metadata:
      labels:
        app: tfm-config-server
    spec:
      containers:
      - name: spring-petclinic-config-server
        image: mintakorion/spring-petclinic-config-server:2.2.2-SNAPSHOT
        ports:
        - containerPort: 8888
        resources:
          limits:
            memory: 512Mi
          requests:
            memory: 128Mi