apiVersion: apps/v1
kind: Deployment
metadata:
  name: tfm-discovery-server
  labels:
    app: tfm-discovery-server

spec:
  replicas: 1
  selector:
    matchLabels:
      app: tfm-discovery-server
  
  template:
    metadata:
      labels:
        app: tfm-discovery-server
    
    spec:
      containers:
      - name: spring-petclinic-discovery-server
        image: nespasec/spring-petclinic-discovery-server:2.2.1
        ports:
        - containerPort: 8761
        resources:
          limits:
            memory: 512Mi
          requests:
            memory: 128Mi