apiVersion: apps/v1
kind: Deployment
metadata:
  name: tfm-api-gateway
  labels:
    app: tfm-api-gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tfm-api-gateway
  template:
    metadata:
      labels:
        app: tfm-api-gateway
    spec:
      containers:
      - name: spring-petclinic-api-gateway
        image: mintakorion/spring-petclinic-api-gateway:2.2.2-SNAPSHOT
        ports:
        - containerPort: 8080
        resources:
          limits:
            memory: 512Mi
          requests:
            memory: 128Mi
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 40
          timeoutSeconds: 2
          periodSeconds: 10
          failureThreshold: 2
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 100
          timeoutSeconds: 2
          periodSeconds: 10
          failureThreshold: 1
