apiVersion: v1
kind: Service
metadata:
  name: tfm-api-gateway-service
  labels:
    type: tfm
spec:
  #type: NodePort
  ports:
    - name: "8080"
      port: 8080
      targetPort: 8080
  selector:
    app: tfm-api-gateway
